project:
  type: website

website:
  title: "Max Czapanskiy | Ecology and Data Science"
  navbar:
    right:
      - href: about.qmd
        text: About
      - teaching.qmd
      - research.qmd
      - href: pubs.qmd
        text: Publications
      - href: posts.qmd
  search: false

format:
  html:
    theme: minty
    css: styles.css
    toc: true

editor: visual

