project:
  type: website

website:
  title: "Max Czapanskiy | Ecology and Data Science"
  navbar:
    right:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - teaching.qmd
      - research.qmd
      - talks.qmd
  search: false

format:
  html:
    theme: minty
    css: styles.css
    toc: true

editor: visual

